Algoritmo "consumo"

Var

       media,distancia,combustivelGasto:real

Inicio

         escreval("Digite a distancia percorrida: ")
         leia(distancia)
         escreval("Digite seu gasto com combustivel: ")
         leia(combustivelGasto)
         
         media <- (distancia / combustivelGasto)
         
         escreval("O Consumo médio foi de: ",media:6:3)

Fimalgoritmo