Algoritmo "fatorial"
// Fazer um programa para ler um número natural N (valor máximo: 15), e
//depois calcular e mostrar o fatorial de N.

Var

   N , Fat, i: inteiro

Inicio

  escreva("Digite o valor de N: ")
  leia(N)

  Fat <- 1
  para i de 1 ate N faca
       Fat <- Fat * i  // Regra da logica para fazer ler um numero anterior e multiplica-lo
       
  fimpara


  escreval("FATORIAL: ",Fat)



Fimalgoritmo