Algoritmo "idade"

Var

    nome1,nome2:caracter
    media,idade1,idade2: real
    

Inicio


      escreval("Digite um nome: ")
      leia(nome1)
      escreval("Digite a idade: ")
      leia(idade1)
      escreval("Digite outro nome: ")
      leia(nome2)
      escreval("Digite a segunda idade: ")
      leia(idade2)
      
      media <- (idade1+idade2) / 2
      
      
      escreval("a idade média entre ",nome1, " e ",nome2," é de ",media:4:2)

Fimalgoritmo