algoritmo "numeros_pares"

var
N, i, pares, qte: inteiro
vet : vetor[0..9] de inteiro

inicio
escreva("Quantos numeros voce vai digitar? : ")
leia(N)


para i de 0 ate N-1 faca
    escreva("Digite um numero: ")
    leia(vet[i])

fimpara

escreval

para i de 0 ate N-1 faca
  se
    pares <- vet[i] % 2 = 0
    escreva(pares)
  fimse
fimpara

para i de 0 ate N-1 faca
    qtd <- 
fimpara

fimalgoritmo